---
- name: Get Device Facts
  hosts: all
  roles:
  - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
  - file:
      path: "/root/config_backup/{{ inventory_hostname }}"
      state: directory
      mode: 0755


  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Get Junos Configuration
    juniper_junos_rpc:
       host: "{{ inventory_hostname }}"
       rpc: get-config
       dest: "/root/config_backup/{{ inventory_hostname }}/config"
       username: root
       password: Gestalt7

  - name: Print commit comment
    debug: msg="{{ mycomment }}"
