---
- name: Get Device Facts
  hosts: all
  roles:
  - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Get Junos Configuration
    juniper_junos_config:
      retrieve: 'committed'
      diff: false
      commit: false
      check: false
      host: "{{ inventory_hostname }}"
      dest: "{{ inventory_hostname }}.xml"
      format: xml
      user: root
      passwd: Gestalt7

  - name: Print commit comment
    debug: msg="{{ mycomment }}"
