---
- name: Get Device Facts
  hosts: all
  roles:
  - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Get Junos Configuration
    junos_get_config:
      host: "{{ inventory_hostname }}"
      logfile: get_config.log
      dest: "{{ inventory_hostname }}.xml"
      format: xml
      user: root
      passwd: Gestalt7

  - name: Print commit comment
    debug: msg="{{ mycomment }}"
