---
- name: Get Device Facts
  hosts: all
  roles:
  - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ junos_device }} port=830 timeout=5

  - name: Get Junos Configuration
    junos_get_config:
      host: "{{ junos_device }}"
      logfile: get_config.log
      dest: "{{ junos_device }}.xml"
      format: xml
      user: root
      passwd: Gestalt7

