---
- name: Get Device Facts
  hosts: all
  roles:
  - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
  - file:
      path: "/root/config_backup/{{ junos_device }}"
      state: directory
      mode: 0755


  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Get Junos Configuration
    juniper_junos_config:
       host: "{{ inventory_hostname }}"
       retrieve: "committed"
       dest: "/root/configuration_backup/{{ junos_device }}/config"
       username: root
       passwd: Gestalt7
  - name: Add file to git
    command: /usr/bin/git add "{{ junos_device }}/config"
    args:
      chdir: /root/configuration_backup

  - name: Commit change
    command: /usr/bin/git commit -m "{{ mycomment }}"
    args:
      chdir: /root/configuration_backup

  - name: Push config file
    command: /usr/bin/git push -u origin master
    args:
      chdir: /root/configuration_backup


  - name: Print commit comment
    debug: msg="{{ mycomment }}"
