---
- name: Get Device Facts
  hosts: all
  roles:
  - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: Retrieve information from devices running Junos OS
    junos_get_facts:  
      host={{ inventory_hostname }}
      user=root
      passwd=Gestalt7
    register: junos
  - name: Show facts
    debug: msg="{{ junos.facts }}"

