---
- name: Gather facts from Junos devices
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Gather Junos facts with no configuration
      juniper_junos_facts:
      register: junos
    - name: Show facts
      debug: 
        var: junos.facts
